### ISSUE TITLE
Anomaly during file system tests

### ISSUE THREAD

**Issue by jigarius** [two-pack/redmine-plugin-test-action#12]
I have a test like this one to ensure that my plugin's root directory is being calculated correctly.
```
test '.root' do
    assert_equal(
      File.join(Rails.root.to_s, 'plugins', 'toggl2redmine'),
      Toggl2Redmine.root
    )
end
```
However, this test fails.

```
Failure:
Toggl2RedmineTest#test_.root [/var/lib/redmine/plugins/toggl2redmine/test/unit/toggl_2_redmine_test.rb:11]:
--- expected
+++ actual
@@ -1,3 +1,3 @@
 # encoding: US-ASCII
 #    valid: true
-"/var/lib/redmine/plugins/toggl2redmine"
+"/var/lib/redmine-plugin"
```

Is the plugin being symlinked to the plugins directory? Is there a possibility to put the plugin in the right place instead of using symlink?

**Comment by two-pack** [comment]
> Is the plugin being symlinked to the plugins directory? Is there a possibility to put the plugin in the right place instead of using symlink?

@jigarius , Yes. And If you does NOT use **actions/checkout** , redmine-plugin-test-action clones your repository on CI.
See #11 .

**Comment by jigarius** [comment]
Thanks! Removing `actions/checkout` fixed the issue.
