### ISSUE TITLE
Support for database matrix

### ISSUE THREAD

**Issue by alexandermeindl** [two-pack/redmine-plugin-test-action#3]
Great action for Redmine plugin testing!

It would be nice to support different database types, like 

```
   matrix:
        db:
          - mysql
          - postgres
          - sqlite3
```

I want to migration from travis to github action and I used this kind of matrix on travis: https://travis-ci.org/github/AlphaNodes/redmine_messenger/jobs/666941581/config

**Comment by two-pack** [comment]
Thank you for the issue🙂
I will try to implement it when I have time, do you think you could submit a pull request for this?

**Comment by alexandermeindl** [comment]
Hi,  I think I would already done it, if there were no docker involved ;) I'am not a "docker"-guy, this mean, this is not an easy task for me. But maybe I'll try it.

**Comment by two-pack** [comment]
I am considering the following specifications.
* Adds new action input parameter, **database**, which is specified type of database like mysql, postgres, sqlite(default).
* Installs database packages(mysql, postgres) in [the base docker image](https://github.com/two-pack/redmine-test-image)
* Adds the command to start database service in [lib/entrypoint.sh](https://github.com/two-pack/redmine-plugin-test-action/blob/master/lib/entrypoint.sh) according to the action input parameter.

Please feel free to comment the idea :)

**Comment by two-pack** [comment]
I implement it for postgresql on a branch, but WIP yet. Details:
* [Docker image which includes postgresql](https://github.com/two-pack/redmine-test-image/tree/add_db_option)
* [Parse database parameter on add_db_option branch in this repository](https://github.com/two-pack/redmine-plugin-test-action/tree/add_db_option)
* [Example of GitHub Action YAML](https://github.com/two-pack/redmine_auto_assign_group/blob/add_db_option/.github/workflows/ci.yml)
    + The result is like following:  
        https://github.com/two-pack/redmine_auto_assign_group/actions/runs/65701845

**NOTE: Now work in progress, so I created docker image for test only v4.1.0 and ruby 2.6.**

I continue to check them and implement for mysql.

**Comment by two-pack** [comment]
I implement it for mysql(mariadb) on a branch, but WIP yet. Details:
See same branches above.
The result is like following:
https://github.com/two-pack/redmine_auto_assign_group/actions/runs/65813160

NOTE: Now work in progress yet, so I created docker image for test only v4.1.0 and ruby 2.6.

I remain to check and fix README and more.

**Comment by two-pack** [comment]
I Implemet it on PR #5 .
