### ISSUE TITLE
Information about used ruby versions

### ISSUE THREAD

**Issue by alexandermeindl** [two-pack/redmine-plugin-test-action#4]
I have a question to used ruby versions. Do these have any special "settings" or compile flags?

My tests on travis (and also local) works:  https://travis-ci.org/AlphaNodes/additionals

But with your github action, I got errors: https://github.com/AlphaNodes/additionals/actions?query=workflow%3A%22Run+Tests%22"

My suggestion is, that [Rails.application.config.after_initialize](https://github.com/AlphaNodes/additionals/blob/master/init.rb#L49) is not working. But I don't know, why. If you can give me information about the used ruby binaries or compiling settings, this would be really helpful.

Just for your info, I use [RVM](https://rvm.io/) and [rbenv](https://github.com/rbenv/rbenv) ruby versions without problems.

**Comment by two-pack** [comment]
> I have a question to used ruby versions.
The action uses [the docker image](https://hub.docker.com/r/twopackas/redmine-test-image) which is based [ruby-slim image](https://hub.docker.com/_/ruby).
The repository of Dockerfile is [here](https://github.com/two-pack/redmine-test-image).

**Comment by alexandermeindl** [comment]
Thanks for this information. I'll try to dig in to find by problem ;)
